# -*- coding: utf-8 -*-
"""tech_stack_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tcuy-2okK_l8Ds_skm5vgBIiUgSFzfD

**Tech Stack Recommender**
"""

import pandas as pd
import numpy as np
import math

data = pd.read_csv("/content/drive/MyDrive/raw_skills.csv")
df = pd.DataFrame(data)
df['skills'] = df['skills'].apply(lambda x: [skill.strip() for skill in x.split(',')])

unique_skills = list(df["skills"].explode().unique())
n_skills = len(unique_skills)
total_roles = len(df)
df.head()

"""**Calculating IDF**"""

idf = []
for i in unique_skills:
    count = 0
    for j in df['skills']:
        if i in j:
            count += 1
    idf.append(math.log(total_roles / count))

idf = np.array(idf)
print(idf)

"""**Calculating tf_idf  & vectors**"""

def vector(skills):
  input_vector = [0] * n_skills
  for skill in skills:
      if skill in unique_skills:
        idx = unique_skills.index(skill)
        tf = 1 / len(skills)
        input_vector[idx] = tf * idf[idx]

  input_vector = np.array(input_vector)
  return input_vector

# input_vector
inputs = ['Docker', 'Kubernetes', 'Terraform']
unique_inputs = list(set(inputs))
input_vector = vector(unique_inputs)
print(input_vector)

db_vectors = []

for i in df['skills']:
  db_vectors.append(vector(i))

print(db_vectors[0])

"""**Cosine Similarity**"""

inp_vect_magnit = np.linalg.norm(input_vector)

db_vect_magnit = []
for i in db_vectors:
  db_vect_magnit.append(np.linalg.norm(i))

db_vect_magnit = np.array(db_vect_magnit)
ab = inp_vect_magnit * db_vect_magnit

print("Input vector magnitude: ", inp_vect_magnit)
print("Database vector magnitude: ", db_vect_magnit)
print("Product of both magnitudes: ", ab)

prodcut_of_vectors = []

for i in db_vectors:
    prodcut_of_vectors.append(np.dot(input_vector, i))

cosine_similarity = prodcut_of_vectors/ab
print(cosine_similarity)

recomended = cosine_similarity.copy()
recomended = np.sort(recomended)[::-1]
recomended = recomended[:3]
print(recomended)

recom_index = []
cos_simi = list(cosine_similarity)
for i in recomended:
  if i in cos_simi:
    recom_index.append(cos_simi.index(i))

print(recom_index)

print("=" * 60)
print("Following are the recommended Roles based on the user input")
print("=" * 60)
print("\nUser Inputs: ", inputs)
print("Recommended Roles: ","\n")

for i in recom_index:
  print(df.iloc[i],'\n')